os:
  - linux

language: php
php:
  - 7.2

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - openssl aes-256-cbc -K $encrypted_48a5fd0d38f7_key -iv $encrypted_48a5fd0d38f7_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - ssh -p 34512 -i ./deploy_key kesatria@hamzah.hideserver.net pwd
  - mysql -e 'create database homestead_test;'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.testing .env
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install --lts
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install
  - php artisan key:generate
  - php artisan migrate:refresh
  - php artisan db:seed

script:
  - phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
  - jshint resources/assets/js/modules/*

deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/deploy.sh
    on:
      branch: master